import { describe, expect, it, afterEach } from "vitest";
import { buildApp, extractTranscript, __cache, processDeduped } from "../src/server.js";

describe("extractTranscript", () => {
  it("takes the last user message", () => {
    expect(
      extractTranscript([
        { role: "system", content: "you are helpful" },
        { role: "user", content: "first" },
        { role: "user", content: "The meeting is Friday." },
      ]),
    ).toBe("The meeting is Friday.");
  });

  it("joins content parts", () => {
    const msgs = [
      { role: "user", content: [{ text: "a" }, { text: "b" }] },
    ];
    expect(extractTranscript(msgs)).toBe("ab");
  });

  it("returns empty when nothing usable", () => {
    expect(extractTranscript([{ role: "user", content: "" }])).toBe("");
  });

  it("unwraps Handy-style <transcript> prompt templates", () => {
    const prompt =
      "<transcript>\nThe meeting is Thursday, sorry, Friday at three.\n</transcript>\n\n" +
      "The above is a transcript generated by a speech-to-text model. Clean it.";
    expect(extractTranscript([{ role: "user", content: prompt }])).toBe(
      "The meeting is Thursday, sorry, Friday at three.",
    );
  });

  it("uses the whole message when no transcript tags exist", () => {
    expect(
      extractTranscript([{ role: "user", content: "Just plain dictation." }]),
    ).toBe("Just plain dictation.");
  });
});

describe("handy endpoints", () => {
  afterEach(() => __cache.clear());

  it("GET /v1/models exposes jev-dictation", async () => {
    const app = buildApp();
    const res = await app.inject({ method: "GET", url: "/v1/models" });
    expect(res.statusCode).toBe(200);
    const body = res.json() as { data: Array<{ id: string }> };
    expect(body.data[0].id).toBe("jev-dictation");
    await app.close();
  });

  // The handler reads the key per request; force the no-key path so this
  // test never touches the network even if the shell has a key exported.
  it("POST /v1/chat/completions passthrough without key", async () => {
    const saved = process.env.OPENROUTER_API_KEY;
    delete process.env.OPENROUTER_API_KEY;
    try {
      const app = buildApp();
      const raw = "The meeting is Friday.";
      const res = await app.inject({
        method: "POST",
        url: "/v1/chat/completions",
        payload: {
          model: "jev-dictation",
          messages: [{ role: "user", content: raw }],
        },
      });
      expect(res.statusCode).toBe(200);
      const body = res.json() as {
        choices: Array<{ message: { content: string }; finish_reason: string }>;
      };
      expect(body.choices[0].finish_reason).toBe("stop");
      expect(body.choices[0].message.content).toBe(raw);
      await app.close();
    } finally {
      if (saved !== undefined) process.env.OPENROUTER_API_KEY = saved;
    }
  });

  it("serves exact repeats from cache without reprocessing", async () => {
    __cache.set("repeat me", "REPEAT ME (cached)");
    const app = buildApp();
    const res = await app.inject({
      method: "POST",
      url: "/v1/chat/completions",
      payload: {
        model: "jev-dictation",
        messages: [{ role: "user", content: "repeat me" }],
      },
    });
    expect(res.statusCode).toBe(200);
    const body = res.json() as {
      choices: Array<{ message: { content: string } }>;
    };
    expect(body.choices[0].message.content).toBe("REPEAT ME (cached)");
    await app.close();
  });

  it("shares one run between concurrent identical transcripts", async () => {
    const saved = process.env.OPENROUTER_API_KEY;
    delete process.env.OPENROUTER_API_KEY;
    try {
      const p1 = processDeduped("concurrent same");
      const p2 = processDeduped("concurrent same");
      expect(p2).toBe(p1);
      expect(await p1).toBe("concurrent same");
      expect(await p2).toBe("concurrent same");
    } finally {
      if (saved !== undefined) process.env.OPENROUTER_API_KEY = saved;
    }
  });

  it("rejects malformed bodies", async () => {
    const app = buildApp();
    const res = await app.inject({
      method: "POST",
      url: "/v1/chat/completions",
      payload: { model: "jev-dictation" },
    });
    expect(res.statusCode).toBe(400);
    await app.close();
  });
});
